[package]
name = "librarian"
version = "0.1.0"
authors = ["Matt Huszagh <huszaghmatt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.6.0"
walkdir = "2.3.2"
